sarugaku/resolvelib

- CHANGELOG.rst
- news/6.feature.rst
- src/resolvelib/reporters.py
- src/resolvelib/resolvers.py
They are not useful at all. Remove them before anyone actually uses them.
> Remove reporting callbacks added in 0.2.1

- src/resolvelib/__init__.py
- src/resolvelib/providers.py
- src/resolvelib/resolvers.py
@techalchemy This is what I was suggesting -- adding an 'AbstractResolver'.
This would basically make resolvelib's resolver-like interface implemented separately (and provide different semantics like PubGrub-based resolution or Molinillo-based resolution).
> Add AbstractResolver class and introduce (and reorganize) 'abstract' subpackage

- tests/conftest.py
- tests/functional/swift-package-manager/inputs/LICENSE
- tests/functional/swift-package-manager/inputs/PerfectHTTPServer.json
- tests/functional/swift-package-manager/inputs/README.md
- tests/functional/swift-package-manager/inputs/SourceKitten.json
- tests/functional/swift-package-manager/inputs/ZewoHTTPServer.json
- tests/functional/swift-package-manager/inputs/kitura.json
- tests/functional/swift-package-manager/test_resolvers.py
I *think* I’ve got most things right, but 3/4 of the resolution results are slightly different (each with one discrepancy). Not sure if this is a functional difference between implementations; will need to look into those.
```python
{'https://github.com/IBM-Swift/BlueSocket.git': '0.12.0'} != {'https://github.com/IBM-Swift/BlueSocket.git': '0.12.4'}
{'https://github.com/IBM-Swift/CCurl.git': '0.3.7'} != {'https://github.com/IBM-Swift/CCurl.git': '0.2.3'}
{'https://github.com/PerfectlySoft/PerfectLib.git': '2.0.0'} != {'https://github.com/PerfectlySoft/PerfectLib.git': '2.0.4'}
{'https://github.com/PerfectlySoft/Perfect-Net.git': '2.0.0'} != {'https://github.com/PerfectlySoft/Perfect-Net.git': '2.0.5'}
{'https://github.com/Zewo/CLibvenice.git': '0.15.0'} != …
```
> Functional tests from Swift Package Manager

- news/18.bugfix.rst
- src/resolvelib/resolvers.py
Fix #18.
This is done by repeatedly restoring old states and fix them one by one, attempting to apply our knowledge on dead criteria:
* Mark candidates pointing to the dead criteria as incompatibilities.
* Remove the dead criterion.
If any of the state can handle these fixes (without causing more incompatibilities), use it as our resume point, and start forward from there.
I was always wondering why all the resolvers need to store a `known_incompatibilities` property. Now I know (I think).
> Backtrack on exhausted candidates

- news/4.bugfix.rst
- src/resolvelib/resolvers.py
- tests/functional/cocoapods/test_resolvers_cocoapods.py
The graph is no longer manipulated during resolution (because we don't need that information anyway). Instead, the graph is only constructed once after resolution is finished. The mapping is also cleaned up after the graph is connected to remove superfluous entries.
Fix #4.
> Clean up state before ending resolution

- src/resolvelib/__init__.py
- src/resolvelib/resolvers.py
- tests/test_resolvers.py
A faulty provider may have its `find_matches()` return candidates that don’t actually return True for `is_satisfied_by()`. This will cause errors difficult to debug down the resolution process, so we make sure to check it at pin time, and raise an error to tell the provider to fix things.
WIP, I want to add a test to make sure we raise this correctly.
Ref #33.
> Ensure the pinned candidate is actually satisfying

- src/resolvelib/resolvers.py
The current backtracking code uses a `RequirementsConflicted` exception to report back to the backtracker that removing one candidate didn't fix the issue. While it's not an unreasonable interpretation of the exception, the control flow is entirely local between `_backtrack` and `excluded_of`. As a result, it makes it harder to reason about the global uses of the `RequirementsConflicted` exception.
This PR changes the control flow to use a `None` return value rather than an exception.
This is (hopefully) the first of a series of PRs to clean up the resolver's exception handling, to make it easier for client code to provide useful diagnostics to the user when resolution fails.
> Avoid using exception for control flow in backtracking

- examples/pypi_wheel_provider.py
- examples/reporter_demo.py
- setup.cfg
- src/resolvelib/compat/collections_abc.py
- src/resolvelib/providers.py
- src/resolvelib/resolvers.py
- tests/functional/cocoapods/test_resolvers_cocoapods.py
- tests/functional/python/test_resolvers_python.py
- tests/functional/swift-package-manager/test_resolvers_swift.py
- tests/test_resolvers.py
WIP, fix #48.
I immediately found a problem with my previous `find_all_matches(identifier)` approach: direct URL requirements. The idea of “all” matches is wrong by itself, since there is no universal set of candidates for a givan identifier.
The approach presented here instead simply presents all requirements known to the resolver at a given point, and ask the provider to return candidates that match all of them. This avoids the universal set problem (every candidate discovery is bounded by at least one requirement).
A side effect is this makes the provider a bit more difficult to implement without hitting the finder over and over again. We probably need to implement some kind of memoisation so multiple searches for the package only hit an index once.
> Introduce iter_matches() to replace find_matches()

- examples/reporter_demo.py
The output of running reporter_demo now looks like:
```
adding_requirement(Requirement(first), None)
starting()
starting_round(0)
adding_requirement(Requirement(second==3.0.0), Candidate(first, 3.0.0))
adding_requirement(Requirement(third==2.0.0), Candidate(first, 3.0.0))
pinning(Candidate(first, 3.0.0))
ending_round(0, ...)
starting_round(1)
adding_requirement(Requirement(third==3.0.0), Candidate(second, 3.0.0))
backtracking(Candidate(first, 3.0.0))
ending_round(1, ...)
starting_round(2)
adding_requirement(Requirement(second==2.0.0), Candidate(first, 2.0.0))
adding_requirement(Requirement(third==1.0.0), Candidate(first, 2.0.0))
pinning(Candidate(first, 2.0.0))
ending_round(2, ...)
starting_round(3)
adding_requirement(Requirement(third==2.0.0), Candidate(second, 2.0.0)) …
```
> Better reporter demo

- README.rst
- examples/extras_provider.py
- examples/pypi_wheel_provider.py
- examples/reporter_demo.py
- src/resolvelib/providers.py
- tests/functional/cocoapods/test_resolvers_cocoapods.py
- tests/functional/python/test_resolvers_python.py
- tests/functional/swift-package-manager/test_resolvers_swift.py
This term has multiple conflicting definitions in this document.
In Candidate:
> Both of "requirement" and "dependency", however, SHOULD NOT be used when describing a Candidate, to avoid confusion.
In Requirement:
> A "dependency", if not clarified otherwise, also refers to this concept.
In this definition:
> A dependency can be either a requirement, or a candidate. In implementations you can treat it as the parent class and/or a protocol of the two.
---
I've opted to remove the single definition at the end, to give us nice and clean "dependency = requirement" naming. We'd likely need to change the variable name in `provider.identify(...)` to something better.
I propose just using `requirement_or_candidate` as the variable name, and avoiding this "pick a name" problem entirely. :P
> Drop the overloading of the "dependency" term

- README.rst
- src/resolvelib/providers.py
It seems to be an overtly specific reminder from back-when-we-were-looking-around-to-understand-what-to-do.
> Reword the cautionary line about "specification" in Monillo

- src/resolvelib/resolvers.py
For pypa/pip#9180. The closure function looks so ugly but I can’t come up with something better :(
> Backtrack if incompatibilities fail to apply

- examples/pypi_wheel_provider.py
- examples/reporter_demo.py
- news/74.feature.rst
- src/resolvelib/providers.py
- src/resolvelib/providers.pyi
- src/resolvelib/resolvers.py
- src/resolvelib/structs.py
- src/resolvelib/structs.pyi
- tests/functional/cocoapods/test_resolvers_cocoapods.py
- tests/functional/python/test_resolvers_python.py
- tests/functional/swift-package-manager/test_resolvers_swift.py
- tests/test_structs.py
My plan is to
* Merge this into master and close #74.
* Create 0.7.0 from master.
* Try integrating 0.7.0 into pip.
* Done?
> Redesign get_preference()

- src/resolvelib/resolvers.py
- tests/functional/cocoapods/test_resolvers_cocoapods.py
- tests/functional/python/test_resolvers_python.py
- tests/functional/swift-package-manager/test_resolvers_swift.py
As per https://github.com/pypa/pip/issues/10479
If pip prefers failure causes then resolvelib must provide them to get_preference
Required for https://github.com/pypa/pip/pull/10481
> Store failure cause and provide to _get_preference

- src/resolvelib/providers.py
Missed AbstractProvider in #84
> Fix AbstractProvider because of #84

- src/resolvelib/providers.pyi
This is based on my reading of the docs:
```
:param backtrack_causes: Sequence of requirement information that were
the requirements that caused the resolver to most recently backtrack.
```
Closes #104.
Signed-off-by: William Woodruff <william@trailofbits.com>
> resolvelib/providers.pyi: add hint for `backtrack_causes`

- src/resolvelib/structs.py
- src/resolvelib/structs.pyi
Result iterable returned by `find_matches()` won't be consumed all at once.
Also unite the `_FactoryIterableView` with `_SequenceIterableView`
With the change, the underlying iterable is guaranteed to be consumed only once.
> Lazy sequence iterview

- tests/functional/python/inputs/index/same-package.json
- tests/functional/python/test_resolvers_python.py
I believe this resolves part of #103. It removes all `LegacyVersion` deprecation warnings for the Python tests. The others are more tricky because they aren't versions for Python packages, therefore they aren't PEP440 compliant. I did not address those for now.
If accepted (within the month of October, which may be a bit of a stretch at this point), might I ask once more to add the [hacktoberfest-accepted](https://hacktoberfest.com/participation/) label to the pull request?
> fixed invalid version specifiers in a test index

- .github/workflows/ci.yml
- noxfile.py
- setup.cfg
- tests/functional/cocoapods/test_resolvers_cocoapods.py
- tests/test_resolvers.py
Because there are test cases against indexes for other languages and their version don't follow the python standards, ~~we have to set version cap of packaging to `<22.0` for testing.~~
Also, switch to `nox` in CI workflows.
* * *
Fixes #114
> CI: fix the CI failures on packaging > 22

- news/113.feature.rst
- src/resolvelib/resolvers.py
- tests/test_resolvers.py
The current backtracking logic assumes that the last state in the stack
is the state that caused the incompatibility. This is not always the case.
For example, given three requirements A, B and C, with dependencies
A1, B1 and C1, where A1 and B1 are incompatible.
The requirements are processed one after the other, so the last state
is related to C, while the incompatibility is caused by B.
The current behavior causes significant slowdowns in case there are
many candidates for B and C, as all their combination are evaluated
before a compatible version of B can be found.
The new behavior discards a state if the packages that cause the
incompatibility are not found among the direct dependencies
of the candidate in the current state.
In our example, this causes the state related to C to be …
> Implement backjumping over unrelated states

- setup.cfg
Resolvelib is not maintained for Python prior to 3.7. It was pointed out in #116.
Resolves #122
> Declare supported Python versions in dist meta

- src/resolvelib/resolvers.py
This will clean up the following stacktrace a little
```
Traceback (most recent call last):
File "/Users/shantanu/.local/pipx/shared/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 316, in _backjump
name, candidate = broken_state.mapping.popitem()
KeyError: 'dictionary is empty'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/Users/shantanu/.local/pipx/shared/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
result = self._result = resolver.resolve(
File "/Users/shantanu/.local/pipx/shared/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
state = resolution.resolve(requirements, max_rounds=max_rounds)
File …
```
> [minor] Improve exception chaining

- src/resolvelib/providers.py
> Clarify the docstrings for `providers.py`

- examples/reporter_demo.py
backtrack_causes is a required argument in get_preferences, as defined by the parent class resolvelib.AbstractProvider. Adding this argument allows the example to run without errors.
> add required arg `backtrack_causes` to `get_preferences()` override

- src/resolvelib/resolvers.py
This is a relatively small thing, but I noticed when you have large backtracking trees the causes list often contains many duplicates and can sometimes be significantly reduced in size (>50%) by deduplicating it.
This saves a bit of memory and some time for any part of the resolution process that is iterating through causes.
> Deduplicate causes

- setup.cfg
Black 24.1.0 has updated the formatting style and it changes several things in the resolvelib codebase: https://github.com/psf/black/releases/tag/24.1.0
In providers.py it changes:
```python
class Preference(Protocol):
def __lt__(self, __other: Any) -> bool:
...
```
To:
```python
class Preference(Protocol):
def __lt__(self, __other: Any) -> bool: ...
```
Which fails the flake8 rule "E704 multiple statements on one line (def)". I am therefore pinning the black version so it does not impact other PRs, and does not fight with flake8. Also in general it makes sense to pin your formatting tool so these breakages don't happen.
I'd also be happy to do a follow up PR that moves the linting and formatting config to `ruff` if the resolvelib maintainers view this as a good idea.
> Fix CI: Pin Black version for linting

- setup.cfg
- tests/functional/cocoapods/test_resolvers_cocoapods.py
While at it, only open the json files once.
(This is motivated by Fedora, when we don't have commentjson packaged. Currently, we use json5 instead, but while looking at that @yselkowitz figured out we can pre-process the files instead.)
> Replace the commentjson test dependency with re.sub

- .github/workflows/ci.yml
- noxfile.py
Makes sure latest actions, OSes, and Python are being tested against.
> Run tests against Python 3.12, 3.13, and use latest version of CI dependencies

- src/resolvelib/resolvers.py
- tests/functional/python/inputs/case/issue-134.json
- tests/functional/python/inputs/index/issue-134.json
Fixes https://github.com/sarugaku/resolvelib/issues/134
Still need to provide a test, going to see if I can write a small provider that can process the JSON in https://github.com/sarugaku/resolvelib/issues/134#issuecomment-2164347177 and follows pip's preference logic. 
But feedback would be welcome.
> Fix backjumping by checking if broken_state.mapping is empty

- tests/functional/python/py2index.py
I was trying to use py2index script for a massive resolution, I ended up making some small changes:
1. Download metadata files directly instead of wheels
2. Skip 404 for project urls (found sometimes got sent to "python" as a dependency)
3. Setup PEP 723 for script, so can run like "uv run py2index.py" without needing to seperately install dependencies.
> Metadata files, skip 404, and PEP 723 support for py2ndex

- src/resolvelib/resolvers.py
- tests/functional/python/inputs/case/backjump-test-1.json
- tests/functional/python/inputs/case/backjump-test-2.json
- tests/functional/python/inputs/index/backjump-test-1.json
- tests/functional/python/inputs/index/backjump-test-2.json
This appears to fix backjumping, in all cases, while keeping the performance benefits.
I do not have an intuitive explanation, but I created a series of tests and printed out debugging information and looked at when the current backjumping made the wrong choice, and it was always when the current broken state's name was not in the incompatible dependencies.
I have added two tests that currently fail that I constructed from my understanding of when the problem occurs.
I have created another test, not in this PR, based on `kedro[test]==0.18.13`, however the JSON is **massive** (450k lines), and it would require a better [`get_preference`](https://github.com/sarugaku/resolvelib/blob/1.0.1/tests/functional/python/test_resolvers_python.py#L74 ) to complete in a reasonable number of rounds. Let …
> Only backjump if the current broken state is an incompatible dependency

- tests/conftest.py
- tests/functional/python/inputs/case/backjump-test-1.json
- tests/functional/python/inputs/case/backjump-test-2.json
- tests/functional/python/test_resolvers_python.py
This adds a new category of functional tests for the Pip Provider which is meant to ensure that backjumping is not accidentally broken.
It checks that certain candidates were never visited, because if backjumping is behaving as expected the path to visit them should have never been taken.
Both test cases added here fail if you remove backjumping.
Later it would be worth adding more of these, in particular I have been work on using "kedro" as a real test case, but am having issues with both py2index and pip-resolver-benchmarks (i.e. pip resolves the real world case but doesn't resolve the version captured by either of these tools), if I ever figure it out I will add more test cases.
> Add unvisited tests to ensure backjumping

- examples/extras_provider.py
- examples/pypi_wheel_provider.py
- examples/reporter_demo.py
- noxfile.py
- pyproject.toml
- src/resolvelib/compat/collections_abc.py
- src/resolvelib/compat/collections_abc.pyi
- src/resolvelib/resolvers.py
- tests/conftest.py
- tests/functional/cocoapods/test_resolvers_cocoapods.py
- tests/functional/python/py2index.py
- tests/functional/python/test_resolvers_python.py
This PR is to switch from flake8 to ruff as the linter, the motivation here is two fold:
* flake8 E704 is not compatible with the black 2024 style - and flake8 maintainers seem uninterested in making this rule compatible with this common style, whereas ruff maintainers seem to be eager to keep in-line with modern black style
* there are many additional rules that come with ruff that can be turned on automatically or easily run manually, and high pace of adding new ones
I may have gone overboard with this PR, let me know if I should make it a minimal transition, but I have split it out hopefully into easily digestible commits.
My biggest concern is https://github.com/sarugaku/resolvelib/commit/949e6120fbc7b714fde71c2118a96d085a69acb2 which moves `_patch_criteria` into it's own method, …
> Switch from flake8 to ruff - and run various linting cleanups

- examples/reporter_demo.py
- examples/visualization/reporter.py
- examples/visualization/run.py
- noxfile.py
- pyproject.toml
- src/resolvelib/__init__.py
- src/resolvelib/providers.py
- src/resolvelib/reporters.py
- src/resolvelib/resolvers/__init__.py
- src/resolvelib/resolvers/abstract.py
- src/resolvelib/resolvers/criterion.py
- src/resolvelib/structs.py
- tests/functional/cocoapods/test_resolvers_cocoapods.py
- tests/functional/python/py2index.py
- tests/functional/python/test_resolvers_python.py
- tests/functional/swift-package-manager/test_resolvers_swift.py
- tests/test_resolvers.py
Signed-off-by: Frost Ming <me@frostming.com>
Supersede #149
> fix: Separate AbstractResolver and Resolver into different modules

- news/129.feature
- news/133.feature
- news/135.feature
- news/136.bugfix
- news/138.bugfix
- news/141.feature
- news/143.feature
- news/150.bugfix
- news/152.bugfix
- news/153.feature
- news/155.bugfix
- news/156.feature
- news/157.feature
- news/158.feature
- news/160.feature
- news/162.bugfix
- news/163.bugfix
- news/164.bugfix
Never done this before, but following up on https://github.com/sarugaku/resolvelib/issues/159#issuecomment-2262070162
I used this script to just pre-populate the NEWS directory and then went through each PR:
```bash
GITHUB_TOKEN="xxx"
git log --pretty="%h - %s" --after="2023-03-09" --grep 'Merge pull request' | grep -oP '#\d+' | grep -oP '\d+' | while read pr; do
curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/sarugaku/resolvelib/pulls/$pr | jq -r '.title' > news/${pr}.bugfix
done
```
Not sure what the style guide is here, just tried my best, can fix anything up as you wish.
> Add news fragments

- news/165.bugfix
- pyproject.toml
This enables the ruff isort rules (I) and sets the location of the projects source, such that the known-first-party ruff isort config is not needed.
> Enable isort via ruff

- news/166.feature
- pyproject.toml
- src/resolvelib/resolvers/abstract.py
- src/resolvelib/resolvers/exceptions.py
- src/resolvelib/resolvers/resolution.py
- tests/test_resolvers.py
This PR builds on top of https://github.com/sarugaku/resolvelib/pull/165
I notice it's a common pattern in this library, and one I prefer, to use `from __future__ import annotations` and guard type hint only imports behind `if TYPE_CHECKING`, this can be implemented automatically with ruff using: `required-imports = ["from __future__ import annotations"]` with the isort rules and the TCH rules: https://docs.astral.sh/ruff/rules/#flake8-type-checking-tch (namely TCH001, TCH002, and TCH003).
I updated the config than then just ran a series of ruff --fix commands for the remaining commits (I have documented them to be clear).
Let me know if this is to your liking or not.
> Guard type hinting via ruff

- news/145.feature
- pyproject.toml
- src/resolvelib/providers.py
- src/resolvelib/resolvers/resolution.py
- tests/functional/python/test_resolvers_python.py
This allows the provider to optimize the steps it takes to choose what to backtrack on.
Specifically the aim is to add preferring conflicting causes in Pip without the overhead of recalculating or caching each time `get_preference` is called. I initially wanted to do a lot of this "preferring" work in resolvelib itself, but upon inspecting the resolution types I realized there was no guarantee of required information (which would have been a problem if this previous PR had landed https://github.com/sarugaku/resolvelib/pull/132).
I have a Pip branch that implements this filtering: https://github.com/notatallshaw/pip/blob/prefer-conflicting-causes/src/pip/_internal/resolution/resolvelib/provider.py#L240. Which on Python 3.8 allows it to solve the following requirement which currently …
> Allow provider to filter unsatisfied names, when backtracking

- .github/workflows/release.yml
Signed-off-by: Frost Ming <me@frostming.com>
Related to #159
> chore(ci): setup automated release workflow

- CHANGELOG.rst
- news/129.feature
- news/133.feature
- news/135.feature
- news/136.bugfix
- news/138.bugfix
- news/141.feature
- news/143.feature
- news/145.feature
- news/150.bugfix
- news/152.bugfix
- news/153.feature
- news/155.bugfix
- news/156.feature
- news/157.feature
- news/158.feature
- news/160.feature
- news/162.bugfix
- news/163.bugfix
- news/164.bugfix
- news/165.bugfix
- news/166.feature
- src/resolvelib/__init__.py
> Release 1.1.0b1

- pyproject.toml
It was never necessary. In the past, `setuptools` would pull it in through the PEP 517 hook, only when building the wheels. During PyCon 2024, though, `wheel` moved into the `setuptools`' codebase and so it's always bundled now, in the modern versions.
> Drop `wheel` from direct build dependencies

- pyproject.toml
Previously, the wheels published to PyPI were being tagged with `py2.py3` implying Python 2 support, despite having `Require-Python: >= 3.7` in the core metadata: https://pypi.org/project/resolvelib/1.1.0/#files. This patch fixes that, forcing the build tool chain to produce wheels only having the `py3` tag in their filenames.
> Configure `setuptools` to produce `py3`-tagged wheels

- .github/workflows/release.yml
This patch adds a clickable link to GitHub web interfaces like https://github.com/sarugaku/resolvelib/actions/runs/11604423758 and https://github.com/sarugaku/resolvelib/deployments/release.
> Display PyPI URL on GH UI when releasing from GHA

- README.rst
This should fix the link on https://pypi.org/project/resolvelib/
Is there a better way to fix this link?
> Fix pypi project page link on README.rst

- .github/workflows/ci.yml
- news/187.significant.rst
- noxfile.py
- pyproject.toml
GitHub Action does not support them anymore. Let’s just drop it and 3.8 since they are EOL anyway.
> Drop support for Python 3.7 and 3.8

- pyproject.toml
- src/resolvelib/resolvers/resolution.py
- tests/functional/python/inputs/case/backjump-test-3.json
- tests/functional/python/inputs/case/backjump-test-4.json
- tests/functional/python/inputs/index/backjump-test-3.json
- tests/functional/python/inputs/index/backjump-test-4.json
- tests/functional/python/test_resolvers_python.py
Fixes https://github.com/sarugaku/resolvelib/issues/180
This implements https://github.com/sarugaku/resolvelib/issues/180#issuecomment-2847584328 with a ratio of 10%.
10% is somewhat arbitrary, but the general idea is optimistic backtracking is supposed to be much faster than regular backtracking, and therefore if it is taking a significant amount of the remaining rounds left it is *probably* going down the wrong path. I tried several different numbers for different max rounds on real world and synthetic cases and found between 5% and 20% tended to work best.
While not intended to be changed I have made `_OPTIMISTIC_BACKJUMPING_RATIO` a global as an easy way for a knowledgeable motivated resolvelib user to pick a different ratio (in particular they may want to pick 0 or 1).
I have added …
> Optimistic backjumping with cutoff
